"""Read script/timeline.json (generated by `make script`) so scenes sync to narration beats."""
from __future__ import annotations
import json
import os
import re
from dataclasses import dataclass, field

LEAD, TAIL = 0.4, 0.3   # must match script/scriptlib.py

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TIMELINE = os.path.join(ROOT, "script", "timeline.json")
SENTENCES = os.path.join(ROOT, "audio", "sentences.json")    # real sentence starts from the TTS (audio/build_audio.py)
_REAL: dict | None = None


def _real_times() -> dict:
    global _REAL
    if _REAL is None:
        try:
            _REAL = json.load(open(SENTENCES))
        except (OSError, ValueError):
            _REAL = {}
    return _REAL


class _Clamped(list):
    """Sentence start times; an index past the end clamps to the last sentence (never IndexError)."""

    def __getitem__(self, i):
        if isinstance(i, int):
            return list.__getitem__(self, max(-len(self), min(i, len(self) - 1)))
        return list.__getitem__(self, i)


@dataclass
class Beat:
    id: str
    start: float          # seconds from chapter start
    dur: float
    kind: str
    vo: str
    shot: str
    scope: list
    sim: list
    verify: list
    terms: list
    abs_start: float = 0.0
    pause: float = 0.0

    @property
    def end(self) -> float:
        return self.start + self.dur

    @property
    def sent(self) -> list:
        """Chapter-relative start time of each narrated sentence (uniform speech rate over the VO window).

        Lets visuals key off the narration: `s = tl['1.02'].sent; st.fade_in(obj, s[2])`."""
        parts = [p for p in re.split(r"(?<=[.?!])\s+", self.vo.strip()) if p]
        real = _real_times().get(self.id)
        if real and len(real) == len(parts):        # measured from the narration audio: preferred
            return _Clamped(list(real))                  # already chapter-relative
        counts = [max(len(p.split()), 1) for p in parts]
        total = sum(counts) or 1
        window = max(self.dur - LEAD - TAIL - self.pause, 0.5)
        out, acc = [], 0
        for c in counts:
            out.append(self.start + LEAD + window * acc / total)
            acc += c
        return _Clamped(out or [self.start + LEAD])

    def at(self, frac: float) -> float:
        """Time at a fraction (0-1) of the beat."""
        return self.start + self.dur * frac


@dataclass
class ChapterTL:
    num: int
    title: str
    abs_start: float
    dur: float
    beats: list = field(default_factory=list)

    def beat(self, bid: str) -> Beat:
        for b in self.beats:
            if b.id == bid:
                return b
        raise KeyError(bid)

    def __getitem__(self, bid: str) -> Beat:
        return self.beat(bid)

    def span(self, first: str, last: str):
        """(start, end) covering beats first..last inclusive."""
        return self.beat(first).start, self.beat(last).end


def load_timeline(path: str = TIMELINE) -> dict:
    return json.load(open(path))


def load_chapter(num: int, path: str = TIMELINE) -> ChapterTL:
    data = load_timeline(path)
    for ch in data["chapters"]:
        if ch["num"] == num:
            tl = ChapterTL(ch["num"], ch["title"], ch["start"], ch["dur"])
            for b in ch["beats"]:
                tl.beats.append(Beat(b["id"], b["start"] - ch["start"], b["dur"], b["kind"], b["vo"], b["shot"],
                                     b["scope"], b["sim"], b["verify"], b["terms"], abs_start=b["start"], pause=b.get("pause", 0.0)))
            return tl
    raise KeyError(num)
