import fs from 'fs';
import { geoConicConformal, geoPath, geoGraticule, geoCircle } from 'd3-geo';
import { feature, mesh } from 'topojson-client';

const topo = JSON.parse(fs.readFileSync('node_modules/world-atlas/countries-50m.json', 'utf8'));
const countries = feature(topo, topo.objects.countries);
const borders = mesh(topo, topo.objects.countries, (a, b) => a !== b);

const W = 2200, H = 2500;
const proj = geoConicConformal().rotate([-15, 0]).center([0, 65.5]).parallels([58, 72]);
// fit: use corner points of the region of interest
const corners = [[-8, 56], [-8, 75], [40, 75], [40, 56], [10, 56], [10, 76], [30, 76], [-2, 58.5]];
proj.scale(1).translate([0, 0]);
let pts = corners.map((c) => proj(c));
let x0 = Math.min(...pts.map((p) => p[0])), x1 = Math.max(...pts.map((p) => p[0])), y0 = Math.min(...pts.map((p) => p[1])), y1 = Math.max(...pts.map((p) => p[1]));
const s = Math.min(W / (x1 - x0), H / (y1 - y0));
proj.scale(s).translate([W / 2 - s * (x0 + x1) / 2, H / 2 - s * (y0 + y1) / 2]);
proj.clipExtent([[-1600, -300], [W + 300, H + 300]]);
const path = geoPath(proj).digits(1);

const inView = (f) => {
  const b = path.bounds(f);
  return b[1][0] > -1600 && b[0][0] < W + 300 && b[1][1] > -300 && b[0][1] < H + 300;
};
const WL = ['Norway','Sweden','Finland','Russia','Denmark','United Kingdom','Ireland','Iceland','Faeroe Is.','Germany','Netherlands','Poland','Lithuania','Latvia','Estonia','Belarus','Belgium','France','Isle of Man','Åland','Jersey','Guernsey'];
const keep = countries.features.filter((f) => WL.includes(f.properties.name) && inView(f));
console.log('countries kept', keep.map((f) => f.properties.name).join(', '));
const land = keep.map((f) => ({ name: f.properties.name, d: path(f) })).filter((x) => x.d);
const bd = path(borders);
const grat = path(geoGraticule().step([5, 2]).extent([[-40, 48], [80, 84]])());
const fields = {
  troll: [3.72, 60.64], asgard: [6.77, 65.1], aasta: [7.2, 67.07], castberg: [20.3, 72.2], norne: [8.08, 66.02],
};
const pins = Object.fromEntries(Object.entries(fields).map(([k, v]) => [k, proj(v).map((n) => +n.toFixed(1))]));
// decorative context fields (approximate positions, unlabeled)
const ctxFields = [[3.21, 56.55], [3.39, 56.27], [1.85, 61.25], [2.2, 61.2], [2.8, 60.5], [2.15, 61.45], [7.3, 65.3], [7.77, 64.35], [5.1, 63.35], [6.55, 65.0], [2.55, 58.85], [2.2, 58.85], [2.5, 59.2], [7.6, 65.7], [1.95, 59.5], [2.5, 61.4], [2.5, 61.0], [21.1, 71.5], [22.3, 71.3], [4.9, 60.9], [3.5, 60.0], [4.3, 61.7], [2.6, 59.7], [5.8, 64.2], [7.9, 66.3], [3.3, 57.2], [4.7, 62.4], [6.2, 64.7]];
const dots = ctxFields.map((c) => proj(c).map((n) => +n.toFixed(1)));
// sea labels
const seas = { north: [1.2, 57.6], norwegian: [0.5, 66.4], barents: [30.0, 74.6] };
const seaPos = Object.fromEntries(Object.entries(seas).map(([k, v]) => [k, proj(v).map((n) => +n.toFixed(1))]));
// scale bar: 500 km at 66N
const a = proj([10, 66]), b = proj([10 + 500 / (111.32 * Math.cos(66 * Math.PI / 180)), 66]);
const km500 = Math.hypot(b[0] - a[0], b[1] - a[1]);
const out = `// GENERATED by tools/mapbuild (world-atlas 50m, d3-geo conic conformal) – do not edit by hand\nexport const MAP = ${JSON.stringify({ w: W, h: H, land, borders: bd, grat, pins, dots, seaPos, km500: +km500.toFixed(1) })};\n`;
fs.writeFileSync('mapdata.js', out);
console.log('written', out.length, 'bytes; pins', JSON.stringify(pins), 'km500', km500.toFixed(1));
